import type { Metadata } from "next";
import { Gasoek_One, Syne } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";

const fontHeading = Gasoek_One ({
  variable: "--font-heading",
  subsets:["latin"],
  weight:["400"],
  display:"swap"
})

const fontBody = Syne({
  variable:"--font-body",
  subsets:["latin"],
  weight:["400","700","800"],
  display:"swap",
})

export const metadata: Metadata = {
  title: "kamuvo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="es"
      className={`${fontHeading.variable} ${fontBody.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
